name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build-win:
        name: build-${{matrix.os}}
        runs-on: windows-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        # Install the .NET Core workload
        - name: Install .NET Core
          uses: actions/setup-dotnet@v4
          with:
              dotnet-version: 8.0.x

        # Restore the application to populate the obj folder with RuntimeIdentifiers
        - name: Restore the application
          run: dotnet restore

        - name: Build
          run: |
              dotnet build -c Release --no-restore
              dotnet publish NeoforgeUpdater.csproj -c Release -r win-x64 -o publish/windows
        
        - name: Archive Release
          uses: thedoctor0/zip-release@0.7.5
          with:
            type: 'zip'
            filename: 'win-x64.zip'
            directory: 'publish/windows'

        - name: Upload build artifacts
          uses: actions/upload-artifact@v3
          with:
              name: Publish Binaries
              path: publish/win-x64.zip
